- mdakits/mdaencore/metadata.yaml
Adding mdaencore. This kit moves the functionality of the MDAnalysis implementation of the ENCORE ensemble similarity analysis method out of the core core library.
> Adding mdaencore

- mdakits/mda-tui/metadata.yaml
TODO: Will need to add a validator for this at some point.
> Switch mda-tui directory to name of project

- mdakits/solvation-analysis/metadata.yaml
Thanks for the straightfoward tutorial, this was a painless process.
My one question is regarding the `run_tests` command. Where should this command be executed from? I've written it to be executed from package root. I am a bit confused by the `pytest --pyargs propkatraj.tests` syntax in the example.
> Register solvation-analysis as MDAKit

- mdakits/maicos/metadata.yaml
MAICoS analyses molecular dynamics simulations of interfacial and confined systems using MDAnalysis methods and the AnalysisBase class.
> Ad MAICoS as an MDAKit

- mdakits/transport-analysis/metadata.yaml
Add transport-analysis as MDAKit, a tool for analysing transport properties including diffusion coefficents.
> Add transport-analysis as MDAKit

- mdakits/pathsimanalysis/metadata.yaml
Adding PathSimAnalysis to the MDAKits registry. This package computes the similarity between molecular dynamics trajectories using the Hausdorff or Fréchet distances.
@orbeckst would you like to be listed as a maintainer?
> Adding PathSimAnalysis

- mdakits/waterdynamics/metadata.yaml
Adding waterdynamics to the MDAKits registry. The waterdynamics package contains functions to analyze water dynamics and water interactions with other molecules in molecular dynamics trajectories.
> Adding waterdynamics

- .github/workflows/gh-ci.yaml
- mdakits/hole2-mdakit/metadata.yaml
Fixes #108 
Bumping up hole2 python version whilst I'm at it, since the pip & conda released versions will also be 3.9+
> Swap out deprecated changed file action

- docs/source/index.rst
- docs/source/troubleshooting.rst
As discussed at the last EOSS4/mdakits meeting: let's have a place in the docs where we can collect troubleshooting solutions and FAQ-style problems. This is just a stub.
> troubleshooting stub page

- mdakits/spyrmsdkit/metadata.yaml
MDAKit to run [spyrmsd](https://github.com/RMeli/spyrmsd) (symmetry-corrected RMSD) on MD trajectories.
> Register spyrmsdkit

- mdakits/lipidorderkit/metadata.yaml
This code allows for the computation of lipid order parameters for all-atom MDAsimulation for researchers that study membrane simulations.
> add lipidorderkit to mdanalysis

- README.rst
- docs/source/about.rst
- docs/source/makingakit.rst
- docs/source/reviewersguide.rst
- mdakits/template/metadata.yaml
It's a lot more than a few yaml changes I'm afraid.
> Add changes needed to make tests and src_install non-optional

- mdakits/zarrtraj/metadata.yaml
Zarrtraj available at 
https://github.com/conda-forge/zarrtraj-feedstock
https://pypi.org/project/zarrtraj/
> Register Zarrtraj

- mdakits/domhmm/metadata.yaml
Dear MDAKit Maintainer/Developers,
I would like to register our recent project **DomHMM** as a MDAKit.
**DomHMM** is a package mainly based on the MDAnalysis library to identify lateral heterogeneities (e.g., liquid-ordered domains) in Molecular Dynamics simulations of lipid bilayers. Our tool is easy to use and should cover a wide range of standard simulation setups (i.e., symmetric and asymmetric membranes, membranes including small proteins). However, this is our first open-source project, and if there is something missing or can be improved, we are open for any suggestions. Note, that we have a documentation describing our package: https://domhmm.readthedocs.io/en/latest/?badge=latest, but more details on the method can be found here: https://doi.org/10.1016/bs.mie.2024.03.006.
The …
> MDAKit registration: DomHMM

- README.rst
- fix #87
- some more README clean-up
> replaced whitepaper with paper DOI in README

- mdakits/pathsimanalysis/metadata.yaml
- close #117 
- update install from PyPi package to conda-forge package installation
> update PathSimAnalysis install command

- mdakits/openmmdl/metadata.yaml
Addition of `OpenMMDL` to `MDAKits`:
Package for Interface to OpenMM for easy setup of molecular dynamic simulations of protein-ligand complexes and the analysis thereof, available at:
https://anaconda.org/conda-forge/openmmdl
> Add openmmdl as MDAKit

- mdakits/mdonatello/metadata.yaml
Addition of `MDonatello` to `MDAKits`:
- Package for 2D small molecule visualization for MDAnalysis, available at:
- https://pypi.org/project/mdonatello/
- https://anaconda.org/conda-forge/mdonatello
> Addition MDonatello to MDAKits

- .github/workflows/gh-ci-cron.yaml
- .github/workflows/gh-ci.yaml
mambaforge is going away and there have been brownouts that are affecting us, see #213
> Switch from mambaforge to miniforge

- mdakits/helanal/metadata.yaml
Adding the helanal MDAkit for analysis of protein helix structure, adapted from the helix_analysis currently in MDAnalysis.
It's up on PyPI; I'm also attempting to get it on conda-forge which has stalled for now, but not needed to get this kit registered.
> Add helanal MDAKit

- mdakits/pytim/metadata.yaml
The latest version (1.0.2) adds compatibility with numpy2 and MDA 2.8, but requires now python>3.1 and mdanalysis >=2.8.0
> updated pytim requirements

- mdakits/menger_curvature/metadata.yaml
Summary :
-  the file was extensively modfied in previous PR  : https://github.com/MDAnalysis/MDAKits/pull/265#issuecomment-2769966558
- the issue with previous fork comes from  commit history: it was messy due to manually runned CI github action in conjonction with multiple fork sync in the middle of the PR 
- It successfully fixed CI dependencies issue were  installing mdanalysis with mamba would install a new version of numpy that was not compatible with numba
Initial PR message : 
Add Menger_Curvature to MDAkit. This project aims to provide a simple MDAkit for JIT accelerated Menger curvature calculation.
The idea is to associate a value of curvature to as many residues as possible in a polymer. If one has access to several conformations , the average value of the curvature (LC) and …
> Add metada.yaml for menger_curvature MDAKit registration (v2)

- docs/source/troubleshooting.rst
* How to fix CI failure on generate_matrix.
* @IAlibay (from discord): "You need to be ahead of main in history. So you'll need to merge in all the commits that have happened in main since the branch."
* see PR #265 as example
> add generate_matrix failure to troubleshooting
